# Bukcore config
# written by Wireless4024

version: 0.1.1
debug: false

fallback_lang: en
# random teleport
rtp:
  enable: true
  cooldown: 30      # second
  delay: 5          # seconds before teleport due generate chunk
  #anchorX: 0        # global setting
  #anchorZ: 0        # global setting
  min-radius: 1000  # global setting
  max-radius: 3000  # global setting
  pre-load-chunks-area: 9  # global setting

  # per world config
  per-world:
    world: # world name
      enable: true      # enable rtp on specifics world
      #cooldown: 60      # cooldown on specifics world
      #anchorX: 0        # anchor x on specifics world
      #anchorZ: 0        # anchor y on specifics world
      #min-radius: 1000  # min radius on specifics world
      #max-radius: 3000  # max radius on specifics world

    # disable rtp on nether and the end
    world_nether:
      enable: false
    world_the_end:
      enable: false

openchest:
  # number of blocks for long range chest open
  range: 80
  # enable to open a chest silently
  # Note : this will duplicate stackable item when right click
  silent: true
sortinv:
  # default: sort item by comparing id/data/amount
  # merge  : merge item inventory when sorting (require PowerNBT)
  mode: merge
# for translation

command: # enabled command
  disabled:
    - test



